name: Publish website to the ddurieux server
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy with rsync
        uses: "Pendect/action-rsyncer@v1.1.0"
        env: 
          DEPLOY_KEY: ${{ secrets.SSH_DOCUMENTATION_KEY }}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: '_site/'
          dest: '${{ secrets.SSH_DOCUMENTATION_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DOCUMENTATION_PATH }}'

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"